version: '3'
services:

  # Web Server
  web:
    build:
      context: .docker
      dockerfile: web.dockerfile
    volumes:
      - ./:/var/www
      - ./.docker/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/v3.ext:/etc/ssl/private/v3.ext
    depends_on:
      - app
    networks:
      default:
        aliases:
          - smart-heritage.lvh.me
    ports:
      - 80:80
      - 443:443

  # Application
  app:
    build:
      context: .docker
      dockerfile: app.dockerfile
    volumes:
      - ./:/var/www
      - appdeps:/var/www/vendor
    depends_on:
      - database
      - redis
    networks:
      - default
    ports:
      - 9000:9000
    stdin_open: true
    tty: true

  # Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      default:
        aliases:
          - db.smart-heritage.lvh.me
    ports:
        - 3306:3306

  # Redis
  redis:
    image: redis:4.0-alpine
    networks:
      default:
        aliases:
          - cache.smart-heritage.lvh.me
    ports:
      - 6379:6379

volumes:
  dbdata:
  appdeps:
